services:
  app:
    image: tolgee/tolgee:v3.183.0
    volumes:
      - ./data:/data
      - ./config.yaml:/config.yaml
    ports:
      - '8089:8080'
    environment:
      spring.config.additional-location: file:///config.yaml
    deploy:
      restart_policy:
        condition: on-failure
  languagetool:
    image: erikvl87/languagetool:6.7
    environment:
      - Java_Xms=256m
      - Java_Xmx=1024m
