build:
    docker build -t toggle-doc
run:
    docker run -d -p 8089:8080 -v ./data:/data -v ./config.yaml:/conf
ig.yaml -e spring.config.additional-location=file:///config.yaml --name to
lgee-app toggle-doc