[supervisord]
nodaemon=true
user=root

[program:languagetool]
# ВИПРАВЛЕНО шлях до /opt/languagetool
command=java -cp /opt/languagetool/languagetool-server.jar org.languagetool.server.HTTPServer --port 8010 --public --allow-origin
directory=/opt/languagetool
autostart=true
autorestart=true
environment=JAVA_OPTS="-Xms256m -Xmx1024m"

[program:tolgee]
command=java -jar /app/app.jar
autostart=true
autorestart=true
environment=spring_config_additional-location="file:///config.yaml"
